name: Check Bicycle Overdue

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check overdue bicycles
        run: |
          curl -X GET https://ptc-bicycle-system.netlify.app/.netlify/functions/check-overdue
