name: Check Bicycle Overdue

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: |
          curl -X GET https://ptc-bicycle-system.netlify.app/.netlify/functions/check-overdue
